openapi: 3.0.0
info:
  title: Social API
  description: API documentation for the Social project
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local server

tags:
  - name: auth
    description: Authentication related endpoints

paths:

  /auth/register:
    post:
      tags:
        - auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                repeat_password:
                  type: string
              required:
                - name
                - email
                - password
                - repeat_password
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
        '409':
          description: User already exists
        '400':
          description: Validation error

  /auth/login:
    post:
      tags:
        - auth
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '404':
          description: User not found
        '403':
          description: Invalid password
        '400':
          description: Validation error

  /auth/send-otp:
    post:
      tags:
        - auth
      summary: Send OTP to user's email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '200':
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: User not found
        '400':
          description: Validation error

  /auth/check-otp:
    post:
      tags:
        - auth
      summary: Check OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
              required:
                - otp
      responses:
        '200':
          description: User is now active
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: OTP not found
        '403':
          description: OTP has expired
        '400':
          description: Validation error

  /auth/reset-password:
    post:
      tags:
        - auth
      summary: Reset password and send new password to user's email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '200':
          description: Password reset token sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: User not found
        '403':
          description: A password reset token has already been sent to your email
        '400':
          description: Validation error

  /auth/confirm-reset-password:
    post:
      tags:
        - auth
      summary: Confirm password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                token:
                  type: string
                newPassword:
                  type: string
              required:
                - email
                - token
                - newPassword
      responses:
        '200':
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Invalid or expired reset token
        '403':
          description: Reset token has expired
        '400':
          description: Validation error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time