openapi: 3.0.0
info:
  title: Social Media API
  description: API documentation for the Social Media project
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: auth
    description: Authentication related endpoints

paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
                  success:
                    type: boolean
        '409':
          description: User already exists
        '400':
          description: Validation error

  /auth/login:
    post:
      tags:
        - auth
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '403':
          description: Invalid password
        '400':
          description: Validation error

  /auth/send-otp:
    post:
      tags:
        - auth
      summary: Send OTP to user's email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: User not found
        '400':
          description: Validation error

  /auth/check-otp:
    post:
      tags:
        - auth
      summary: Check OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
      responses:
        '200':
          description: User is now active
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: OTP not found
        '403':
          description: OTP has expired
        '400':
          description: Validation error

  /auth/reset-password:
    post:
      tags:
        - auth
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset token sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: User not found
        '403':
          description: Password reset token already sent
        '400':
          description: Validation error

  /auth/confirm-reset-password:
    post:
      tags:
        - auth
      summary: Confirm password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                token:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: Invalid or expired reset token
        '403':
          description: Reset token has expired
        '400':
          description: Validation error

  /auth/verify-token:
    post:
      tags:
        - auth
      summary: Verify JWT token
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
                  success:
                    type: boolean
        '403':
          description: Token expired
        '401':
          description: Invalid token

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        title:
          type: string
        bio:
          type: string
        post_count:
          type: integer
        email:
          type: string
        slug:
          type: string
        img:
          type: string
        follower_count:
          type: integer
        following_count:
          type: integer
        task_done:
          type: integer
        project_done:
          type: integer
        img_bg:
          type: string