openapi: 3.0.0
info:
  title: Test API
  description: API documentation for the Test project
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: test
    description: Test related endpoints

paths:
  /test/upload:
    post:
      tags:
        - test
      summary: Upload an image to Cloudinary
      description: Uploads an image file and returns the Cloudinary URL of the uploaded image.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: The image file to upload.
      responses:
        '200':
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    description: The URL of the uploaded image on Cloudinary.
        '400':
          description: No image file provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No image file provided"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to upload image"